// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/15/2025, 8:01:54 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/plugins/**/*.{js,ts,mjs}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/composables/**/*.{js,ts,mjs}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/utils/**/*.{js,ts,mjs}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/paulbugeon/PYOH/sdavesne - Sophie Davesne Vitrine/sdavesne-front/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;